# Site settings

title: 折纸大学开源软件镜像站
school: 折纸大学
brand: PPUC Open Source Mirror
operator: 折纸大学信息化技术中心
author: PPUC University WithOut Association
desc: 致力于为国内和校内用户提供高质量的开源软件镜像、Linux 镜像源上游服务，帮助用户更方便地获取开源软件。本镜像站由折纸大学没有协会负责运行维护。
logo: flase
meow_404: true
issue_tag: tuna
baseurl: "" # the subpath of your site, e.g. /blog
permalink: "/:categories/:title/"
url: "https://mirror.ppuc.lol"
hostname: "mirror.ppuc.lol"
urlv4: "https://mirror4.ppuc.lol"
urlv6: "https://mirror6.ppuc.lol"
hide_navbar: false
hide_download: false
hide_server_status: true

hide_mirrorz: true
mirrorz_desc: 校园网联合镜像站
mirrorz_link: "https://mirrors.cernet.edu.cn/list"
mirrorz_help_link: "https://help.mirrors.cernet.edu.cn/"


# ==================================
# Build settings below, DO NOT TOUCH
# ==================================

highlighter: rouge
markdown: kramdown
kramdown:
    input: GFM
    hard_wrap: false

vite:
    config_path: _src/vite.json
    viteConfig: _vite.config.mjs

plugins:
    - jekyll-relative-links
    - jekyll-sitemap
    - jekyll/fontawesome/svg
    - jekyll-minifier

jekyll-minifier:
    exclude: [ 'assets/*' ]

exclude: [gen_robot.sh, geninfo/, gen_desc.py]
addition_exclude:
    - package.json
    - package-lock.json
    - node_modules/
    - Gemfile
    - Gemfile.lock
    - README.md
    - vendor/
    - Dockerfile*
    - LICENSE

# vim: ts=2 sts=2 sw=2 expandtab
